FROM postgres:16

COPY app/postgres/init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432

HEALTHCHECK --interval=5s --timeout=3s --start-period=10s --retries=20 \
  CMD pg_isready -U postgres || exit 1
