"""cycles

Revision ID: 17237df9be5c
Revises: 9615a5440e5c
Create Date: 2026-05-11 22:47:22.386042

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17237df9be5c'
down_revision: str | Sequence[str] | None = '9615a5440e5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_cycles_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cycles')),
    sa.UniqueConstraint('team_id', 'number', name='uq_cycles_team_number')
    )
    with op.batch_alter_table('issues') as batch_op:
        batch_op.add_column(sa.Column('cycle_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(op.f('fk_issues_cycle_id_cycles'), 'cycles', ['cycle_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues') as batch_op:
        batch_op.drop_constraint(op.f('fk_issues_cycle_id_cycles'), type_='foreignkey')
        batch_op.drop_column('cycle_id')
    op.drop_table('cycles')
    # ### end Alembic commands ###
