"""customer_requests

Revision ID: 2628ffe08ba7
Revises: f13cbdff0084
Create Date: 2026-05-12 00:13:49.533416

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2628ffe08ba7'
down_revision: str | Sequence[str] | None = 'f13cbdff0084'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'linked', 'resolved', 'canceled', name='customer_request_status'), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_customer_requests_issue_id_issues'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_customer_requests_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_requests'))
    )
    op.create_index(op.f('ix_customer_requests_issue_id'), 'customer_requests', ['issue_id'], unique=False)
    op.create_index(op.f('ix_customer_requests_workspace_id'), 'customer_requests', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_requests_workspace_id'), table_name='customer_requests')
    op.drop_index(op.f('ix_customer_requests_issue_id'), table_name='customer_requests')
    op.drop_table('customer_requests')
    # ### end Alembic commands ###
