"""notifications

Revision ID: 5b892353743a
Revises: 17237df9be5c
Create Date: 2026-05-11 23:03:29.194651

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b892353743a'
down_revision: str | Sequence[str] | None = '17237df9be5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('assigned', 'status_changed', 'commented', 'mentioned', 'subscribed', name='notification_kind'), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=True),
    sa.Column('comment_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['members.id'], name=op.f('fk_notifications_actor_id_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_notifications_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_notifications_issue_id_issues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['members.id'], name=op.f('fk_notifications_recipient_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_notifications_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
