"""initiatives

Revision ID: 77db8fddc740
Revises: 5b892353743a
Create Date: 2026-05-11 23:17:44.926086

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77db8fddc740'
down_revision: str | Sequence[str] | None = '5b892353743a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initiatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('slug_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_color', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'canceled', name='initiative_status'), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['members.id'], name=op.f('fk_initiatives_owner_id_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_initiatives_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initiatives'))
    )
    op.create_index(op.f('ix_initiatives_slug_id'), 'initiatives', ['slug_id'], unique=True)
    op.create_index(op.f('ix_initiatives_workspace_id'), 'initiatives', ['workspace_id'], unique=False)
    with op.batch_alter_table('projects') as batch_op:
        batch_op.add_column(sa.Column('initiative_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(op.f('fk_projects_initiative_id_initiatives'), 'initiatives', ['initiative_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects') as batch_op:
        batch_op.drop_constraint(op.f('fk_projects_initiative_id_initiatives'), type_='foreignkey')
        batch_op.drop_column('initiative_id')
    op.drop_index(op.f('ix_initiatives_workspace_id'), table_name='initiatives')
    op.drop_index(op.f('ix_initiatives_slug_id'), table_name='initiatives')
    op.drop_table('initiatives')
    # ### end Alembic commands ###
