"""triage

Revision ID: 97eb03ae086a
Revises: 77db8fddc740
Create Date: 2026-05-11 23:33:17.469020

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97eb03ae086a'
down_revision: str | Sequence[str] | None = '77db8fddc740'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('is_triage', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('issues', sa.Column('triage_source', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'triage_source')
    op.drop_column('issues', 'is_triage')
    # ### end Alembic commands ###
