"""add_conditional_fields

Revision ID: a2b114d7139b
Revises: ed26906c1a31
Create Date: 2026-05-07 20:46:51.070726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b114d7139b'
down_revision: Union[str, None] = 'ed26906c1a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('conditional_on', sa.String(length=128), nullable=True))
    op.add_column('fields', sa.Column('conditional_value', sa.String(length=256), nullable=True))
    op.add_column('fields', sa.Column('conditional_action', sa.String(length=16), nullable=True))
    op.add_column('fields', sa.Column('formula', sa.Text(), nullable=True))
    op.add_column('fields', sa.Column('decimal_places', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'decimal_places')
    op.drop_column('fields', 'formula')
    op.drop_column('fields', 'conditional_action')
    op.drop_column('fields', 'conditional_value')
    op.drop_column('fields', 'conditional_on')
    # ### end Alembic commands ###
