"""p1 polish: subscribers, project_teams, project_resources

Revision ID: a67395f62899
Revises: 7890d5f1b3e4
Create Date: 2026-05-12 21:19:10.445177

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67395f62899'
down_revision: str | Sequence[str] | None = '7890d5f1b3e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_resources_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_resources'))
    )
    op.create_index(op.f('ix_project_resources_project_id'), 'project_resources', ['project_id'], unique=False)
    op.create_table('project_teams',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_teams_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_project_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'team_id', name=op.f('pk_project_teams'))
    )
    op.create_table('issue_subscribers',
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_subscribers_issue_id_issues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_issue_subscribers_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', 'member_id', name=op.f('pk_issue_subscribers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_subscribers')
    op.drop_table('project_teams')
    op.drop_index(op.f('ix_project_resources_project_id'), table_name='project_resources')
    op.drop_table('project_resources')
    # ### end Alembic commands ###
