"""add_advanced_envelope_options

Revision ID: ed26906c1a31
Revises: 0012_add_priv_msg_recip
Create Date: 2026-05-07 19:06:05.259832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed26906c1a31'
down_revision: Union[str, None] = '0012_add_priv_msg_recip'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envelopes', sa.Column('allow_comments', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('envelopes', sa.Column('responsive_signing', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('envelopes', sa.Column('allow_reassign', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_envelopes_folder_id'), 'envelopes', ['folder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_envelopes_folder_id'), table_name='envelopes')
    op.drop_column('envelopes', 'allow_reassign')
    op.drop_column('envelopes', 'responsive_signing')
    op.drop_column('envelopes', 'allow_comments')
    # ### end Alembic commands ###
