/**
 * Locator Map — Generated from research/normalized/locator-hints.json
 * Use these selectors in Playwright tests for stable element targeting.
 */
export const LOCATORS: Record<string, Record<string, string>> = {
  "mail-inbox": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search_for_email__meetings__fi": "[aria-label=\"Search for email, meetings, files and more.\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]",
  "people": "[aria-label=\"People\"]"
  },
  "mail-reading-pane": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search_for_email__meetings__fi": "[aria-label=\"Search for email, meetings, files and more.\"]",
  "chat": "[aria-label=\"Chat\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]"
  },
  "mail-compose": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search_for_email__meetings__fi": "[aria-label=\"Search for email, meetings, files and more.\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]",
  "people": "[aria-label=\"People\"]"
  },
  "mail-sent": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search_for_email__meetings__fi": "[aria-label=\"Search for email, meetings, files and more.\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]",
  "people": "[aria-label=\"People\"]"
  },
  "mail-drafts": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search_for_email__meetings__fi": "[aria-label=\"Search for email, meetings, files and more.\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]",
  "people": "[aria-label=\"People\"]"
  },
  "mail-search": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search_for_email__meetings__fi": "[aria-label=\"Search for email, meetings, files and more.\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]",
  "people": "[aria-label=\"People\"]"
  },
  "mail-folders-sidebar": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search_for_email__meetings__fi": "[aria-label=\"Search for email, meetings, files and more.\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]",
  "people": "[aria-label=\"People\"]"
  },
  "calendar-month": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search": "[aria-label=\"Search\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]",
  "people": "[aria-label=\"People\"]"
  },
  "calendar-week": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search": "[aria-label=\"Search\"]",
  "chat": "[aria-label=\"Chat\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]"
  },
  "calendar-day": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search": "[aria-label=\"Search\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]",
  "people": "[aria-label=\"People\"]"
  },
  "calendar-workweek": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search": "[aria-label=\"Search\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]",
  "people": "[aria-label=\"People\"]"
  },
  "calendar-new-event": {
  "skip_to_main_content": "[aria-label=\"Skip to main content\"]",
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "search": "[aria-label=\"Search\"]",
  "chat": "[aria-label=\"Chat\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]"
  },
  "contacts-list": {
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "chat": "[aria-label=\"Chat\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]",
  "people": "[aria-label=\"People\"]",
  "to_do": "[aria-label=\"To Do\"]"
  },
  "contacts-detail": {
  "app_launcher": "[aria-label=\"App launcher\"]",
  "axiom_global_technologies": "[aria-label=\"Axiom Global Technologies\"]",
  "outlook": "[aria-label=\"Go to Outlook\"]",
  "onenote_feed": "[aria-label=\"OneNote feed\"]",
  "my_day": "[aria-label=\"My Day\"]",
  "_": "[aria-label=\"Notifications\"]",
  "_": "[aria-label=\"Settings\"]",
  "ta": "[aria-label=\"Account manager for TechBrig Alerts\"]",
  "sign_in": "[aria-label=\"Sign in\"]",
  "mail": "[aria-label=\"Mail\"]",
  "calendar": "[aria-label=\"Calendar\"]",
  "copilot": "[aria-label=\"Copilot\"]",
  "people": "[aria-label=\"People\"]",
  "to_do": "[aria-label=\"To Do\"]",
  "newsletters": "[aria-label=\"Newsletters\"]"
  },
  "tasks-list": {
  "no_thanks": "[aria-label=\"No thanks\"]",
  "try_edge": "[aria-label=\"Try Edge\"]",
  "all_microsoft_expand_to_see_li": "[aria-label=\"All Microsoft expand to see list of Microsoft products and services\"]",
  "close_search": "[aria-label=\"Close search\"]",
  "microsoft": "[aria-label=\"Microsoft\"]",
  "see_more_menu_options": "[aria-label=\"See more menu options\"]",
  "see_more_menu_options": "[aria-label=\"See more menu options\"]",
  "more": "[aria-label=\"More\"]",
  "search_expanded": "[aria-label=\"Search Expanded\"]",
  "search": "[aria-label=\"Search or ask a question\"]",
  "cancel": "[aria-label=\"Cancel Search\"]",
  "cart": "[aria-label=\"0 items in shopping cart\"]",
  "sign_in_to_your_account_sign_i": "[aria-label=\"Sign in to your account\"]",
  "download__for_android": "[aria-label=\"Download  for Android\"]",
  "download__for_windows": "[aria-label=\"Download  for Windows\"]"
  },
  "settings-general": {

  },
  "settings-mail": {

  },
  "settings-signatures": {

  },
  "settings-rules": {

  },
  "settings-oof": {

  },
  "settings-categories": {

  }
};
